//Data for pojects - displayed on Potfolio page
export const projectsData = [
    {
      id: 1,
      title: "Portfolio Website",
      description: "Portfolio website showcasing skills & experience.",
      image: "/images/portfolio-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/PortfolioWebsite",
    },
    {
      id: 2,
      title: "Dev-Quiz",
      description: "Quiz web application that uses ChatGPT.",
      image: "/images/dev-quiz-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/DevQuiz",
    },
    {
      id: 3,
      title: "Portfolio Game",
      description: "Interactive portfolio game.",
      image: "/images/portfolio-game-thumb.png",
      tag: ["All", "UI"],
      projectPageURL: "/Portfolio/PortfolioGame",
    },
    {
      id: 4,
      title: "Survey-Send",
      description: "Email survey web application.",
      image: "/images/survey-send-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/SurveySend",
    },
    {
      id: 5,
      title: "HTML Emails",
      description: "Custom HTML email templates.",
      image: "/images/custom-emails-thumb.png",
      tag: ["All", "Email"],
      projectPageURL: "/Portfolio/HTMLEmails",
    },
    {
      id: 6,
      title: "WCAG Demo",
      description: "Web Content Accessibility Guidelines demo.",
      image: "/images/wcag-demo-thumb.png",
      tag: ["All", "UI"],
      projectPageURL: "/Portfolio/WCAGDemo",
    },
    {
      id: 7,
      title: "Everyday Homes",
      description: "Real Estate website.",
      image: "/images/everyday-homes-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/EverydayHomes",
    },
    {
      id: 8,
      title: "YouTube Player",
      description: "YouTube player web application.",
      image: "/images/youtube-player-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/YouTubePlayer",
    },
    {
      id: 9,
      title: "Joes BBQ",
      description: "Restaurant website.",
      image: "/images/joes-bbq-thumb.png",
      tag: ["All", "Web"],
      projectPageURL: "/Portfolio/JoesBBQ",
    },
  ];