export const projectsData = [
    {
      id: 1,
      title: "Project 1",
      description: "Project 1 description",
      image: "/images/1.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "/",
    },
    {
      id: 2,
      title: "Project 2",
      description: "Project 2 description",
      image: "/images/1.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "/",
    },
    {
      id: 3,
      title: "Project 3",
      description: "Project 3 description",
      image: "/images/1.jpg",
      tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "/",
    },
    {
      id: 4,
      title: "Project 4",
      description: "Project 4 description",
      image: "/images/1.jpg",
      tag: ["All", "UI"],
      gitUrl: "/",
      previewUrl: "/",
    },
    {
      id: 5,
      title: "Project 5",
      description: "Project 5 description",
      image: "/images/1.jpg",
      tag: ["All", "UI"],
      gitUrl: "/",
      previewUrl: "/",
    },
    {
      id: 6,
      title: "Project 6",
      description: "Project 6 description",
      image: "/images/1.jpg",
      tag: ["All", "Email"],
      gitUrl: "/",
      previewUrl: "/",
    },
  ];